<html>

<head>

<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">

<?PHP
echo " <title>$c Business Categories</title>\n";
echo " </head>\n";

echo " <body>\n";
echo " <table width=\"100%\" bgcolor=\"#FFFFD2\" cellspacing=\"0\" style=\"border-top:1px groove #C0C0C0; border-bottom-style:groove\">\n";
echo "     <tr>\n";
echo "       <td width=\"100%\"><b><font face=\"Verdana\" size=\"5\">&nbsp;$c  Yellow Pages \n";
        
        
        
echo "        </font></b></td></tr></table>\n";
?>

<table border="0" width="100%">
  <tr>

    <td>
    <p align="center">
    
  <?php
echo "       <b><font face=\"Verdana\" color=\"#7A7999\" size=\"1\">Search $c, $DATABASE_NAME Yellow Pages</font> </b><br>\n";
      
echo " <center>     <form style=\"margin: 0px\" action=\"cq.php\" method=get> \n";
echo "              <input name=c type=hidden value=\"$c\">\n";
echo "              <input size=35 name=q type=text value=\"\">\n";
echo "              <input type=submit value=\"Search $c YP\"></center></form>\n";
    
?>  
    
    
    
    </td>
  </tr>
  </table>

<table border="0" width="100%" cellpadding="0" cellspacing="0">
  <tr>


  <td width="100%" valign="top"><blockquote><br><font size="3" face="verdana">Available Business Categories</font><br><br>
<font size="2" face="verdana">


<?php
echo" <a href=\"cq.php?c=$c&q=Accountants\">Accountants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Adhesives and Sealants\">Adhesives and Sealants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Adoption Agencies\">Adoption Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Adult and Continuing Education\">Adult and Continuing Education</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Adult Entertainment\">Adult Entertainment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Advertising - All\">Advertising - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Advertising Agencies and Counselors\">Advertising Agencies and Counselors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aeronautical Engineers\">Aeronautical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aerospace Industries\">Aerospace Industries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Agricultural Engineers\">Agricultural Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Air Conditioning and Heating\">Air Conditioning and Heating</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Air Conditioning Contractors and Systems\">Air Conditioning Contractors and Systems</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Air Freight and Package Express Service\">Air Freight and Package Express Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aircraft Charter Rental and Leasing\">Aircraft Charter Rental and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aircraft Equipment and Supplies\">Aircraft Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aircraft Instruction\">Aircraft Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aircraft Servicing and Maintenance\">Aircraft Servicing and Maintenance</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aircraft\">Aircraft</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Airline Ticket Agencies\">Airline Ticket Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Airlines\">Airlines</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Airport Transportation and Parking Services\">Airport Transportation and Parking Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Airports\">Airports</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Alcoholism Information and Treatment Centers\">Alcoholism Information and Treatment Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Allergists\">Allergists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Alterations and Tailoring\">Alterations and Tailoring</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Alternative Medicine\">Alternative Medicine</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ambulance Services\">Ambulance Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=American Restaurants\">American Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Amusement and Water Parks\">Amusement and Water Parks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Animal Hospitals and Clinics\">Animal Hospitals and Clinics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Animal Shelters\">Animal Shelters</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Antiques\">Antiques</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Apartment Rentals and Roommate Agencies\">Apartment Rentals and Roommate Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Apartments - Furnished\">Apartments - Furnished</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Apartments\">Apartments</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Appliances - Household - Major\">Appliances - Household - Major</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Appliances - Household - Service and Repair\">Appliances - Household - Service and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Appliances - Small - Service and Repair\">Appliances - Small - Service and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Appliances - Small\">Appliances - Small</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aquariums\">Aquariums</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Arbitration and Mediation\">Arbitration and Mediation</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Arcades\">Arcades</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Archery\">Archery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Architects\">Architects</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Architectural Engineers\">Architectural Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Army and Navy Goods\">Army and Navy Goods</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Art Galleries and Dealers\">Art Galleries and Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Art Schools\">Art Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Art Supplies\">Art Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Arthritis Specialists\">Arthritis Specialists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Artists' Materials and Supplies\">Artists' Materials and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Arts and Crafts Shops\">Arts and Crafts Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Arts Organizations and Information\">Arts Organizations and Information</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Asian Markets\">Asian Markets</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Associations Societies and Foundations\">Associations Societies and Foundations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Astrology and Numerology\">Astrology and Numerology</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Athletic Clubs and Organizations\">Athletic Clubs and Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Athletic Wear\">Athletic Wear</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auctioneers\">Auctioneers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auctions\">Auctions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Audio-Visual Equipment\">Audio-Visual Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Antiques and Classics\">Auto Antiques and Classics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Body Work\">Auto Body Work</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Buyers\">Auto Buyers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Dealers - New Cars\">Auto Dealers - New Cars</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Dealers - Used Cars\">Auto Dealers - Used Cars</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Inspection Services\">Auto Inspection Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Painting and Repair\">Auto Painting and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Parts - Used and Rebuilt\">Auto Parts - Used and Rebuilt</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Parts and Supplies\">Auto Parts and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Racing and Race Tracks\">Auto Racing and Race Tracks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Radio and Stereo Systems\">Auto Radio and Stereo Systems</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Renting and Leasing\">Auto Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Repair and Service\">Auto Repair and Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Restoration\">Auto Restoration</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Security\">Auto Security</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Transmissions\">Auto Transmissions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Auto Transport\">Auto Transport</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Automobile Auctions\">Automobile Auctions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Automobile Wrecking\">Automobile Wrecking</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Automotive Engineers\">Automotive Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Aviation Consultants\">Aviation Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Baby Accessories\">Baby Accessories</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bagel Shops\">Bagel Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bail Bonds\">Bail Bonds</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bakers and Bakeries\">Bakers and Bakeries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Balloons and Novelties\">Balloons and Novelties</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Banks - All\">Banks - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Banks - Commercial\">Banks - Commercial</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Banquet Facilities\">Banquet Facilities</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Barbecue Equipment and Supplies\">Barbecue Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Barbecue Restaurants\">Barbecue Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Barbers\">Barbers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bars and Taverns\">Bars and Taverns</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Baseball Clubs and Parks\">Baseball Clubs and Parks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bathroom Planning and Remodeling\">Bathroom Planning and Remodeling</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Beauty Salons Equipment and Supplies\">Beauty Salons Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Beauty Salons\">Beauty Salons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Beauty Schools\">Beauty Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bed and Breakfast Accommodations and Inns\">Bed and Breakfast Accommodations and Inns</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Beer\">Beer</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Beverages\">Beverages</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bicycle Dealers\">Bicycle Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bicycle Equipment and Supplies\">Bicycle Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bicycle Repair\">Bicycle Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bicycles - Tours and Renting\">Bicycles - Tours and Renting</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Billiards and Pool\">Billiards and Pool</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Biomedical Engineers\">Biomedical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Blood Banks and Centers\">Blood Banks and Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boat Builders and Yards\">Boat Builders and Yards</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boat Dealers\">Boat Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boat Equipment and Supplies\">Boat Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boat Excursions\">Boat Excursions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boat Repairing\">Boat Repairing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boats - Charter and Rental\">Boats - Charter and Rental</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Book Binders and Book Printers\">Book Binders and Book Printers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Book Dealers - Used and Rare\">Book Dealers - Used and Rare</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Book Dealers\">Book Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Book Publishers\">Book Publishers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bookkeeping Service\">Bookkeeping Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Botanical Gardens\">Botanical Gardens</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bowling Centers\">Bowling Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boxes - Corrugated and Fiber\">Boxes - Corrugated and Fiber</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boxes - Paper\">Boxes - Paper</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Boxing Clubs and Instruction\">Boxing Clubs and Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Brake Service\">Brake Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Breakfast Restaurants\">Breakfast Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Brew Pubs\">Brew Pubs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Brewers\">Brewers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bridal Shops\">Bridal Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Building Contractors\">Building Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Building Materials and Supplies\">Building Materials and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Building Materials\">Building Materials</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Buildings - Metal\">Buildings - Metal</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Burglar Alarm Systems and Equipment\">Burglar Alarm Systems and Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Bus Lines\">Bus Lines</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Buses - Charter and Rental\">Buses - Charter and Rental</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Business and Trade Organizations\">Business and Trade Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Business and Vocational Schools\">Business and Vocational Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Business Brokers\">Business Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Business Consultants\">Business Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cabinet Makers\">Cabinet Makers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cable Television Companies\">Cable Television Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cable Television Service\">Cable Television Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cafeterias\">Cafeterias</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cajun Restaurants\">Cajun Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Campgrounds and Recreational Vehicle Parks\">Campgrounds and Recreational Vehicle Parks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Campgrounds\">Campgrounds</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Camping Equipment\">Camping Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Camps\">Camps</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Candy and Confectionery\">Candy and Confectionery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Canoes and Kayaks\">Canoes and Kayaks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Car Financing and Loans\">Car Financing and Loans</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Car Washing and Polishing\">Car Washing and Polishing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cardiologists\">Cardiologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Career Counseling\">Career Counseling</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Carnivals\">Carnivals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Carpenters\">Carpenters</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Carpet Rug and Linoleum Dealers\">Carpet Rug and Linoleum Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Carpet and Rug Cleaners\">Carpet and Rug Cleaners</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Carpet and Rug Installation and Repair\">Carpet and Rug Installation and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Caskets and Urns\">Caskets and Urns</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Caterers\">Caterers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cellular Mobile and Wireless Telephones\">Cellular Mobile and Wireless Telephones</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cemeteries\">Cemeteries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chambers of Commerce\">Chambers of Commerce</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Check Cashing Services\">Check Cashing Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cheese and Dairy\">Cheese and Dairy</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chemical Engineers\">Chemical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chemicals - Manufacturers\">Chemicals - Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Childcare Services and Facilities\">Childcare Services and Facilities</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Children's and Infant Wear\">Children's and Infant Wear</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chimneys - Builders Cleaners and Repairers\">Chimneys - Builders Cleaners and Repairers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chinese Restaurants\">Chinese Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Chiropractors\">Chiropractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Church Supplies\">Church Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Churches and Religious Organizations\">Churches and Religious Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Churches\">Churches</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cigar Cigarette and Tobacco Dealers\">Cigar Cigarette and Tobacco Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Civil Engineers\">Civil Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cleaners\">Cleaners</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cleaning - Household\">Cleaning - Household</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cleaning - Office\">Cleaning - Office</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Climbing and Hiking Equipment and Supplies\">Climbing and Hiking Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clinics\">Clinics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clocks - Dealers and Repair\">Clocks - Dealers and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clothing - Wholesale and Manufacturers\">Clothing - Wholesale and Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clothing Accessories - Other\">Clothing Accessories - Other</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clothing\">Clothing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clowns\">Clowns</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Clubs\">Clubs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cocktail Lounges\">Cocktail Lounges</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Coffee and Tea\">Coffee and Tea</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Coffee Shops\">Coffee Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Collectibles\">Collectibles</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Collection Agencies\">Collection Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Comedy Clubs\">Comedy Clubs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Comic Books\">Comic Books</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Commercial Printing\">Commercial Printing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer and Equipment Dealers\">Computer and Equipment Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Communications Consultants\">Computer Communications Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Consultants\">Computer Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Furniture\">Computer Furniture</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Graphics\">Computer Graphics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Manufacturers\">Computer Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Networking\">Computer Networking</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Parts and Supplies\">Computer Parts and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Peripherals - Manufacturers\">Computer Peripherals - Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Printers\">Computer Printers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Renting and Leasing\">Computer Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Repair\">Computer Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Software and Services\">Computer Software and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer System Designers\">Computer System Designers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Computer Training\">Computer Training</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Concrete Contractors\">Concrete Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Concrete\">Concrete</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Condominiums\">Condominiums</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Consignment Shops\">Consignment Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Construction Companies\">Construction Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Construction Machinery and Equipment\">Construction Machinery and Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Consulates and Foreign Offices\">Consulates and Foreign Offices</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Consulting Engineers\">Consulting Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Contact Lenses\">Contact Lenses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Contractors - Equipment and Supplies\">Contractors - Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Convenience Stores\">Convenience Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Convention and Meeting Facilities and Services\">Convention and Meeting Facilities and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Conversions\">Conversions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Copying and Duplicating Services\">Copying and Duplicating Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Copying Machines and Supplies\">Copying Machines and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cosmetics and Perfumes\">Cosmetics and Perfumes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Costumes\">Costumes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Counseling Services\">Counseling Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Courier and Delivery Service\">Courier and Delivery Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Court Reporting Services\">Court Reporting Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Courts\">Courts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Craft Supplies\">Craft Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Credit and Debt Counseling Services\">Credit and Debt Counseling Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Credit Cards and Other Credit Plans\">Credit Cards and Other Credit Plans</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Credit Reporting Agencies\">Credit Reporting Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Credit Unions\">Credit Unions</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cremation\">Cremation</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Crisis Intervention Services\">Crisis Intervention Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Cruises\">Cruises</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dance Companies\">Dance Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dance Instruction\">Dance Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dancing Instruction\">Dancing Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Data Processing Services\">Data Processing Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Delicatessens\">Delicatessens</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dentists\">Dentists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Department Stores\">Department Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dermatologists\">Dermatologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Desktop Publishing\">Desktop Publishing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Developmental Health Services\">Developmental Health Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Diaper Services\">Diaper Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Direct Mail Advertising\">Direct Mail Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Directory and Guide Advertising\">Directory and Guide Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Disc Jockeys\">Disc Jockeys</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Discount Stores\">Discount Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Diving\">Diving</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Doughnuts\">Doughnuts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Driving Instruction\">Driving Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Drug Abuse Addiction Information and Treatment\">Drug Abuse Addiction Information and Treatment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Drug Stores and Pharmacies\">Drug Stores and Pharmacies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Drug Stores\">Drug Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dry Cleaners and Laundries\">Dry Cleaners and Laundries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Dry Wall Contractors\">Dry Wall Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Educational Consultants\">Educational Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electric Companies\">Electric Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electric Equipment and Supplies\">Electric Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electrical Contractors\">Electrical Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electrical Engineers\">Electrical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electricians\">Electricians</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Electronic Equipment and Supplies\">Electronic Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Elementary and Middle Schools\">Elementary and Middle Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Elevator Repair\">Elevator Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Embassies\">Embassies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Embroidery\">Embroidery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Employment Agencies and Opportunities\">Employment Agencies and Opportunities</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Employment Contractors – Temporary Help\">Employment Contractors – Temporary Help</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Endocrinologists\">Endocrinologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Energy Conservation Engineers\">Energy Conservation Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Engineers - All\">Engineers - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Entertainers - All\">Entertainers - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Entertainment Bureaus\">Entertainment Bureaus</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Environmental and Ecological Conservation\">Environmental and Ecological Conservation</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Environmental and Ecological Products and Services\">Environmental and Ecological Products and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Environmental Engineers\">Environmental Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Escort Services\">Escort Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Escrow Services\">Escrow Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Estate Planning - Administration\">Estate Planning - Administration</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=European Restaurants\">European Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Event Planners\">Event Planners</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Excavating Contractors\">Excavating Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Executive Search Consultants\">Executive Search Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Exercise and Physical Fitness Programs\">Exercise and Physical Fitness Programs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Exercise Equipment\">Exercise Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Exporters\">Exporters</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Extreme Sports - Parachuting Bungee Jumping\">Extreme Sports - Parachuting Bungee Jumping</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fabric Shops\">Fabric Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fabrics - Wholesale\">Fabrics - Wholesale</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Factory Outlet Stores\">Factory Outlet Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fairs and Festivals\">Fairs and Festivals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Family Planning Services\">Family Planning Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Farm Equipment\">Farm Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Farmers Markets\">Farmers Markets</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fast Food Restaurants\">Fast Food Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fax Machines and Service\">Fax Machines and Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fence Contractors\">Fence Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fencing\">Fencing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ferries and Water Taxis\">Ferries and Water Taxis</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fertility Clinics\">Fertility Clinics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Filing Equipment\">Filing Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Financial Advisory Services\">Financial Advisory Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Financial Planning Consultants\">Financial Planning Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Financing\">Financing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fire Alarm Systems and Equipment\">Fire Alarm Systems and Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fire Departments\">Fire Departments</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fireplaces\">Fireplaces</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fishing Areas\">Fishing Areas</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fishing Guides Charters and Parties\">Fishing Guides Charters and Parties</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fishing Tackle Dealers\">Fishing Tackle Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Flea Markets\">Flea Markets</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Floor Laying Refinishing and Resurfacing\">Floor Laying Refinishing and Resurfacing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Florists\">Florists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Flowers Plants and Gifts\">Flowers Plants and Gifts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Flowers - Wholesale\">Flowers - Wholesale</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Food Brokers\">Food Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Food Delivery Services\">Food Delivery Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Food Processors and Manufacturers\">Food Processors and Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Foods - Carry Out\">Foods - Carry Out</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Football Clubs and Instruction\">Football Clubs and Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Formal Wear\">Formal Wear</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fraternal Organizations\">Fraternal Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Freight Forwarding\">Freight Forwarding</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=French Restaurants\">French Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Fruits and Vegetables\">Fruits and Vegetables</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Funeral Directors and Homes\">Funeral Directors and Homes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture - Cleaning Refinishing and Repair\">Furniture - Cleaning Refinishing and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture - Office\">Furniture - Office</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture - Outdoor\">Furniture - Outdoor</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture - Used\">Furniture - Used</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture Dealers\">Furniture Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture Manufacturers\">Furniture Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture Renting and Leasing\">Furniture Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Furniture Upholstery\">Furniture Upholstery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gambling and Casinos\">Gambling and Casinos</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Garages and Carports\">Garages and Carports</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Garden Centers\">Garden Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gas - Propane\">Gas - Propane</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gas Companies\">Gas Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gastroenterologists\">Gastroenterologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=General Contractors\">General Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=General Practice\">General Practice</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Geological Engineers\">Geological Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Geriatric Care\">Geriatric Care</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gift Baskets and Parcels\">Gift Baskets and Parcels</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gifts - All\">Gifts - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Giftwares - Wholesale\">Giftwares - Wholesale</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Glass - Auto Plate and Window\">Glass - Auto Plate and Window</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Courses - Miniature\">Golf Courses - Miniature</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Courses - Private\">Golf Courses - Private</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Courses - Public\">Golf Courses - Public</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Equipment and Supplies\">Golf Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Instruction\">Golf Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Golf Practice Ranges\">Golf Practice Ranges</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gourmet Shops\">Gourmet Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Government Offices and County Clerks\">Government Offices and County Clerks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Grain Elevators\">Grain Elevators</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Graphic Designers\">Graphic Designers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Greek Restaurants\">Greek Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Greenhouses\">Greenhouses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Greeting Cards\">Greeting Cards</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Grocers and Supermarkets\">Grocers and Supermarkets</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Guest Houses\">Guest Houses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Guns and Gunsmiths\">Guns and Gunsmiths</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gutters and Downspouts\">Gutters and Downspouts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gymnastics\">Gymnastics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Gynecologists and Obstetricians\">Gynecologists and Obstetricians</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hair Removal Replacement and Products\">Hair Removal Replacement and Products</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Halls and Auditoriums\">Halls and Auditoriums</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Handbags\">Handbags</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hardware Stores\">Hardware Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hats and Caps\">Hats and Caps</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Health and Diet Foods\">Health and Diet Foods</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Health Clubs and Gyms\">Health Clubs and Gyms</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Health Services\">Health Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hearing Aids\">Hearing Aids</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Heating and Ventilating Contractors\">Heating and Ventilating Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Herbs and Spices\">Herbs and Spices</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=High Schools\">High Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Historical Places\">Historical Places</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hobby and Model Construction\">Hobby and Model Construction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hockey Clubs and Instruction\">Hockey Clubs and Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Home and Building Inspection Services\">Home and Building Inspection Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Home Brewing\">Home Brewing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Home Builders\">Home Builders</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Home Health Services\">Home Health Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Home Improvement Centers\">Home Improvement Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Horse and Carriage Rides and Rentals\">Horse and Carriage Rides and Rentals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Horse Dealers Boarding and Rental\">Horse Dealers Boarding and Rental</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Horse Equipment Supplies Service and Training\">Horse Equipment Supplies Service and Training</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hosiery and Socks\">Hosiery and Socks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hospices\">Hospices</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hospital Supplies\">Hospital Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hospitals\">Hospitals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hostels\">Hostels</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hot Air Balloons\">Hot Air Balloons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hot Tubs and Spas\">Hot Tubs and Spas</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hotels and Motels\">Hotels and Motels</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Housewares\">Housewares</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Housing Authorities and Agencies\">Housing Authorities and Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Human Factors Engineers\">Human Factors Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Human Relations Counselors\">Human Relations Counselors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Human Services Organizations\">Human Services Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Hydraulic Engineers\">Hydraulic Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ice Cream and Frozen Dessert Shops\">Ice Cream and Frozen Dessert Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ice Cream and Frozen Desserts\">Ice Cream and Frozen Desserts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ice Hockey\">Ice Hockey</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Importers\">Importers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Indian Restaurants\">Indian Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Industrial Technical and Trade Schools\">Industrial Technical and Trade Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Industrial and Commercial Machinery\">Industrial and Commercial Machinery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Industrial Engineers\">Industrial Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insulation Materials\">Insulation Materials</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Agents and Brokers\">Insurance - Agents and Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - All\">Insurance - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Automotive\">Insurance - Automotive</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Consultants and Advisors\">Insurance - Consultants and Advisors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Home\">Insurance - Home</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Inspection Services\">Insurance - Inspection Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Life\">Insurance - Life</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Medical\">Insurance - Medical</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Insurance - Property and Casualty\">Insurance - Property and Casualty</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Interior Decorators Designers and Consultants\">Interior Decorators Designers and Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet and Online Services\">Internet and Online Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet Advertising\">Internet Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet Marketing Services\">Internet Marketing Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet Products and Services\">Internet Products and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet Service Providers (ISPs)\">Internet Service Providers (ISPs)</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internet Services - Electronic Commerce\">Internet Services - Electronic Commerce</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Internists\">Internists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Investigators\">Investigators</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Investment Advisory Service\">Investment Advisory Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Investment Securities\">Investment Securities</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Invitations and Announcements\">Invitations and Announcements</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Irish Restaurants\">Irish Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Italian Restaurants\">Italian Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Janitorial Services\">Janitorial Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Japanese Restaurants\">Japanese Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Jewelers\">Jewelers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Jewelry Repair\">Jewelry Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Job Training Services\">Job Training Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Juices\">Juices</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Junior Colleges and Technical Institutes\">Junior Colleges and Technical Institutes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Kennels and Pet Boarding\">Kennels and Pet Boarding</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Korean Restaurants\">Korean Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Kosher Restaurants\">Kosher Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Kosher\">Kosher</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Labor Organizations\">Labor Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Laboratories - Medical\">Laboratories - Medical</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Laboratories - Research and Development\">Laboratories - Research and Development</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Laboratories - Testing\">Laboratories - Testing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Landscape Contractors\">Landscape Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Landscaping Equipment and Supplies\">Landscaping Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Language Schools\">Language Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawn and Grounds Maintenance\">Lawn and Grounds Maintenance</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawn Mowers\">Lawn Mowers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Adoption Divorce and Family Law\">Lawyers - Adoption Divorce and Family Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - All\">Lawyers - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Appeal\">Lawyers - Appeal</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Bankruptcy Law\">Lawyers - Bankruptcy Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Business Corporation and Partnership Law\">Lawyers - Business Corporation and Partnership Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Civil Law\">Lawyers - Civil Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Commercial and Banking Law\">Lawyers - Commercial and Banking Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Contract and Construction Law\">Lawyers - Contract and Construction Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Criminal Law\">Lawyers - Criminal Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Discrimination and Civil Rights Law\">Lawyers - Discrimination and Civil Rights Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Domestic Relations and Family Law\">Lawyers - Domestic Relations and Family Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - DUI and Traffic Law\">Lawyers - DUI and Traffic Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Elder Law\">Lawyers - Elder Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Employment and Labor Law\">Lawyers - Employment and Labor Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Environmental and Natural Resources Law\">Lawyers - Environmental and Natural Resources Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Immigration Naturalization and Customs\">Lawyers - Immigration Naturalization and Customs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Insurance Law and Coverage\">Lawyers - Insurance Law and Coverage</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Malpractice Law and Negligence\">Lawyers - Malpractice Law and Negligence</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Patent Trademark and Copyright\">Lawyers - Patent Trademark and Copyright</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Personal Injury Property Damage and Wrongful Death\">Lawyers - Personal Injury Property Damage and Wrongful Death</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Real Estate\">Lawyers - Real Estate</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Social Security and Government Law\">Lawyers - Social Security and Government Law</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Trial Lawyers\">Lawyers - Trial Lawyers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Wills Estates Trusts and Probate\">Lawyers - Wills Estates Trusts and Probate</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Lawyers - Workers Compensation\">Lawyers - Workers Compensation</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Legal Counsel and Services\">Legal Counsel and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Legal Services\">Legal Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Libraries\">Libraries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Machine Shops\">Machine Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Magazine Publishers\">Magazine Publishers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Magicians\">Magicians</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mail Order and Catalog Shopping\">Mail Order and Catalog Shopping</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mailing and Shipping Services\">Mailing and Shipping Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Management Consultants\">Management Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Management Engineers\">Management Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Manicures and Pedicures\">Manicures and Pedicures</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Manufacturers Engineers\">Manufacturers Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Marinas\">Marinas</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Marine Engineers\">Marine Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Marine Equipment and Supplies\">Marine Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Market Research and Analysis\">Market Research and Analysis</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Marketing Consultants\">Marketing Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Marriage and Family Counselors\">Marriage and Family Counselors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Martial Arts\">Martial Arts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Masonry Contractors\">Masonry Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mass Transit\">Mass Transit</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Massage Therapists\">Massage Therapists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Massage Therapy\">Massage Therapy</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Maternity Apparel\">Maternity Apparel</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mattresses\">Mattresses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Maxillofacial\">Maxillofacial</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Meat\">Meat</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mechanical Contractors\">Mechanical Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mechanical Engineers\">Mechanical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Medical Equipment and Supplies\">Medical Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Medical Insurance\">Medical Insurance</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Medical Waste Management\">Medical Waste Management</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Men's Clothing\">Men's Clothing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mental Health Services\">Mental Health Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Metal Fabricators\">Metal Fabricators</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Metal\">Metal</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mexican Restaurants\">Mexican Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Middle Eastern Restaurants\">Middle Eastern Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Midwives\">Midwives</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Military\">Military</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mobile Home Dealers\">Mobile Home Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mobile Homes - Dealers\">Mobile Homes - Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mobile Homes - Parks and Communities\">Mobile Homes - Parks and Communities</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Modeling Agencies\">Modeling Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Money Orders\">Money Orders</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Monuments and Markers\">Monuments and Markers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mortgage Bankers and Correspondents\">Mortgage Bankers and Correspondents</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mortgage Brokers\">Mortgage Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mortgages\">Mortgages</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mosques\">Mosques</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Motion Pictures Producers Studios and Video Production\">Motion Pictures Producers Studios and Video Production</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Motorcycle and Motor Scooter Dealers\">Motorcycle and Motor Scooter Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Motorcycles and Motor Scooters - Repair and Service\">Motorcycles and Motor Scooters - Repair and Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Motorcycles and Motor Scooters - Supplies\">Motorcycles and Motor Scooters - Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Movers\">Movers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Moving Supplies and Equipment - Renting\">Moving Supplies and Equipment - Renting</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mufflers and Exhaust Systems\">Mufflers and Exhaust Systems</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Museums\">Museums</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Music Instruction\">Music Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Musical Instruments\">Musical Instruments</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Musicians Bands and Orchestras\">Musicians Bands and Orchestras</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Mutual Funds\">Mutual Funds</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nail Salons\">Nail Salons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=National Guard\">National Guard</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Natural and Organic Foods\">Natural and Organic Foods</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Neurologists\">Neurologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Newspaper Advertising\">Newspaper Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Newspaper Publishers\">Newspaper Publishers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Night Clubs\">Night Clubs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Non-profit Organizations\">Non-profit Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Notaries\">Notaries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nurse Practitioners\">Nurse Practitioners</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nurseries Plants and Trees\">Nurseries Plants and Trees</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nursery Schools Preschools and Kindergartens\">Nursery Schools Preschools and Kindergartens</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nurses\">Nurses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nursing and Life Care Homes\">Nursing and Life Care Homes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Nutritionists\">Nutritionists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Office Furniture and Equipment\">Office Furniture and Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Office Supplies\">Office Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Oil and Gas Exploration and Development\">Oil and Gas Exploration and Development</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Oil and Lubrication\">Oil and Lubrication</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Oils - Fuel\">Oils - Fuel</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Oncologists\">Oncologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Opera Companies\">Opera Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ophthalmologists\">Ophthalmologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Optical Engineers\">Optical Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Optical Goods\">Optical Goods</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Optometrists\">Optometrists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Orthopedic Shoes and Appliances\">Orthopedic Shoes and Appliances</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Orthopedics\">Orthopedics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Osteopathy\">Osteopathy</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Otolaryngology\">Otolaryngology</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Outdoor and Billboard Advertising\">Outdoor and Billboard Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Package Designing and Development\">Package Designing and Development</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pagers and Beepers\">Pagers and Beepers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Paint Supplies\">Paint Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Painting Contractors\">Painting Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Parking Lots Stations and Garages\">Parking Lots Stations and Garages</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Parks\">Parks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Party Planning Services\">Party Planning Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Party Supplies\">Party Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Patio Builders\">Patio Builders</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Paving Contractors\">Paving Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pawn Brokers\">Pawn Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pediatricians\">Pediatricians</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Periodicals Publishers\">Periodicals Publishers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pest Control\">Pest Control</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Cemeteries\">Pet Cemeteries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Shops\">Pet Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Sitting Services\">Pet Sitting Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Supplies and Accessories\">Pet Supplies and Accessories</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Training\">Pet Training</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pet Washing and Grooming\">Pet Washing and Grooming</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pharmaceutical Manufacturers\">Pharmaceutical Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pharmaceuticals\">Pharmaceuticals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Philanthropy\">Philanthropy</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Photo Labs\">Photo Labs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Photographers\">Photographers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Photographic Equipment - Repairing\">Photographic Equipment - Repairing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Photographic Equipment and Supplies\">Photographic Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Physical Therapists\">Physical Therapists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Physician and Surgeon Information and Referral Service\">Physician and Surgeon Information and Referral Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Physicians and Surgeons\">Physicians and Surgeons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Picture Frames - Dealers\">Picture Frames - Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Picture Frames\">Picture Frames</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pizza\">Pizza</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Plastic Surgeons\">Plastic Surgeons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Plastics and Plastic Products - Manufacturers\">Plastics and Plastic Products - Manufacturers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Plumbers\">Plumbers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Plumbing Contractors\">Plumbing Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Podiatrists\">Podiatrists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Police Departments\">Police Departments</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Political Organizations\">Political Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pollution Assessment and Remediation\">Pollution Assessment and Remediation</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Post Offices\">Post Offices</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Pottery\">Pottery</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Poultry\">Poultry</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Printing Services\">Printing Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Private Schools\">Private Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Produce\">Produce</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Production and Specialties Advertising\">Production and Specialties Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Professional Engineers\">Professional Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Promotional Products Advertising\">Promotional Products Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Psychiatrists\">Psychiatrists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Psychics\">Psychics</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Psychologists\">Psychologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Public Libraries\">Public Libraries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Public Relations Counselors\">Public Relations Counselors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Public Schools\">Public Schools</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Publishers - All\">Publishers - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Publishers - Books\">Publishers - Books</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Race Tracks\">Race Tracks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Radio and Audio Advertising\">Radio and Audio Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Radio Communication Equipment and Systems\">Radio Communication Equipment and Systems</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Radio Stations and Broadcasting Companies\">Radio Stations and Broadcasting Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Radiologists\">Radiologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Railroads\">Railroads</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate - All\">Real Estate - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate - Commercial and Investment\">Real Estate - Commercial and Investment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Agents\">Real Estate Agents</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Appraisers\">Real Estate Appraisers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Buyers and Brokers\">Real Estate Buyers and Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Consultants\">Real Estate Consultants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Developers\">Real Estate Developers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Inspection Services\">Real Estate Inspection Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Lawyers\">Real Estate Lawyers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Loans\">Real Estate Loans</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Real Estate Management\">Real Estate Management</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recording Services - Sound and Video\">Recording Services - Sound and Video</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recording Studios\">Recording Studios</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Records Tapes and Compact Discs\">Records Tapes and Compact Discs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recreation Centers\">Recreation Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recreational Trips and Tours\">Recreational Trips and Tours</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recreational Vehicle Dealers\">Recreational Vehicle Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recreational Vehicle Renting and Leasing\">Recreational Vehicle Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recreational Vehicles\">Recreational Vehicles</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recruitment\">Recruitment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Recycling Services\">Recycling Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Refrigeration Equipment\">Refrigeration Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Rehabilitation Services\">Rehabilitation Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Relocation Service\">Relocation Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Remodeling and Repairing Contractors\">Remodeling and Repairing Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Rental Agencies - Property\">Rental Agencies - Property</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Rental Service - Stores and Yards\">Rental Service - Stores and Yards</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Resale Shops\">Resale Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Resorts and Vacation Rentals\">Resorts and Vacation Rentals</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Restaurant Equipment and Supplies\">Restaurant Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Restaurants - All\">Restaurants - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Resume Services\">Resume Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Retirement Communities and Homes\">Retirement Communities and Homes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Retirement Planning Consultants and Services\">Retirement Planning Consultants and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Riding Academies\">Riding Academies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Road Side Services\">Road Side Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Roof Cleaning and Maintenance\">Roof Cleaning and Maintenance</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Roofing Contractors\">Roofing Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Roofing Equipment and Supplies\">Roofing Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Rubbish and Garbage Removal\">Rubbish and Garbage Removal</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=RV Parks and Campgrounds\">RV Parks and Campgrounds</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=School Supplies\">School Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Schools - All\">Schools - All</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Scrap Metals and Iron\">Scrap Metals and Iron</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Screen Printing\">Screen Printing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Seafood Restaurants\">Seafood Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Seafood\">Seafood</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Security Guard and Patrol Service\">Security Guard and Patrol Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Security Systems\">Security Systems</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Senior Services\">Senior Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Service Stations\">Service Stations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sheet Metal Work Contractors\">Sheet Metal Work Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sheet Music\">Sheet Music</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sheriffs\">Sheriffs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Shoe Repairing\">Shoe Repairing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Shoes and Boots\">Shoes and Boots</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Shopping Centers and Malls\">Shopping Centers and Malls</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Siding Contractors\">Siding Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sightseeing Tours\">Sightseeing Tours</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Signs\">Signs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Skateboarding and Rollerblading\">Skateboarding and Rollerblading</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Skating Equipment\">Skating Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Skating Rinks\">Skating Rinks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ski and Snowboard Dealers\">Ski and Snowboard Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ski Resorts\">Ski Resorts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Skin Care\">Skin Care</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Snowmobiles\">Snowmobiles</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Soccer\">Soccer</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Social Service and Welfare Organizations\">Social Service and Welfare Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Social Workers\">Social Workers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Soft Drinks\">Soft Drinks</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Spanish Restaurants\">Spanish Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Spas and Saunas\">Spas and Saunas</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Special Academic Education\">Special Academic Education</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sporting Goods\">Sporting Goods</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sports Bars\">Sports Bars</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sports Cards and Memorabilia\">Sports Cards and Memorabilia</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sports Medicine\">Sports Medicine</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sprinklers - Garden and Lawn\">Sprinklers - Garden and Lawn</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Sprinklers\">Sprinklers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stables\">Stables</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stadiums Arenas and Athletic Fields\">Stadiums Arenas and Athletic Fields</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stationers\">Stationers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Steak Houses\">Steak Houses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Steel - Distributors and Warehouses\">Steel - Distributors and Warehouses</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stereos\">Stereos</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stock and Bond Brokers\">Stock and Bond Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Storage - Household and Commercial\">Storage - Household and Commercial</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Storage - Self Service\">Storage - Self Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Stress Management\">Stress Management</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Structural Engineers\">Structural Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Surveyors - Land\">Surveyors - Land</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Swimming Pool Contractors Dealers and Designers\">Swimming Pool Contractors Dealers and Designers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Swimming Pool Equipment and Supplies\">Swimming Pool Equipment and Supplies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Swimwear\">Swimwear</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Synagogues\">Synagogues</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Systems and Integration Engineers\">Systems and Integration Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Take Out\">Take Out</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Talent Agencies\">Talent Agencies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tanning Salons\">Tanning Salons</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tattooing and Body Piercing\">Tattooing and Body Piercing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tax Returns Consultants and Representatives\">Tax Returns Consultants and Representatives</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Taxicabs and Transportation Services\">Taxicabs and Transportation Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telecommunications Services\">Telecommunications Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telemarketing\">Telemarketing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telephone Communications Services\">Telephone Communications Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telephone Equipment - Service and Repair\">Telephone Equipment - Service and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telephone Equipment and Systems Dealers\">Telephone Equipment and Systems Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Telephone Service\">Telephone Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Television and Radio - Service and Repair\">Television and Radio - Service and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Television Advertising\">Television Advertising</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Television Dealers\">Television Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Television Stations and Broadcasting Cooperatives\">Television Stations and Broadcasting Cooperatives</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tennis Courts\">Tennis Courts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tennis Equipment\">Tennis Equipment</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tennis Instruction\">Tennis Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Thai Restaurants\">Thai Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Theatres - Live\">Theatres - Live</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Theatres - Movie\">Theatres - Movie</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Thrift Shops\">Thrift Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Ticket Sales\">Ticket Sales</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tile and Ceramic Contractors\">Tile and Ceramic Contractors</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tile and Ceramic Dealers\">Tile and Ceramic Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tire Dealers\">Tire Dealers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Title Companies\">Title Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tool and Die Makers\">Tool and Die Makers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tourist Attractions and Information\">Tourist Attractions and Information</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tours - Operators and Promoters\">Tours - Operators and Promoters</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Towing\">Towing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Toys\">Toys</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Traffic and Transportation Engineers\">Traffic and Transportation Engineers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trailer Renting and Leasing\">Trailer Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trailers - Camping and Travel\">Trailers - Camping and Travel</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Travel Agencies and Bureaus\">Travel Agencies and Bureaus</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tree Service\">Tree Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Truck Dealers - New\">Truck Dealers - New</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Truck Dealers - Used\">Truck Dealers - Used</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Truck Parts\">Truck Parts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Truck Renting and Leasing\">Truck Renting and Leasing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Truck Repairing and Service\">Truck Repairing and Service</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trucking - Dump\">Trucking - Dump</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trucking - Hauling\">Trucking - Hauling</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trucking - Motor Freight\">Trucking - Motor Freight</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trucking Brokers\">Trucking Brokers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Trucking Companies\">Trucking Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=T-Shirts\">T-Shirts</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Tutoring\">Tutoring</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Uniforms\">Uniforms</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Universities and Colleges\">Universities and Colleges</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Urologists\">Urologists</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Used and Vintage Clothes\">Used and Vintage Clothes</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Variety Stores\">Variety Stores</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Vegetarian Restaurants\">Vegetarian Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Vending Machines\">Vending Machines</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Veteran and Military Organizations\">Veteran and Military Organizations</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Veterinarians\">Veterinarians</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Video Games\">Video Games</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Video Production and Taping Services\">Video Production and Taping Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Video Tapes and Discs\">Video Tapes and Discs</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Vietnamese Restaurants\">Vietnamese Restaurants</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wallpaper\">Wallpaper</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Warehouses - Merchandise and Self Storage\">Warehouses - Merchandise and Self Storage</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Watches - Dealers and Repair\">Watches - Dealers and Repair</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Water - Bottled and Bulk\">Water - Bottled and Bulk</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Water and Sewage Companies\">Water and Sewage Companies</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Water Skiing\">Water Skiing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Water Sports Instruction\">Water Sports Instruction</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Web Site Design Services\">Web Site Design Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wedding Chapels\">Wedding Chapels</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wedding Supplies and Services\">Wedding Supplies and Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Weight Control Services\">Weight Control Services</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Welding\">Welding</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Western Apparel\">Western Apparel</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wigs and Hair Pieces\">Wigs and Hair Pieces</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wildlife Centers\">Wildlife Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Window Glass Coating and Tinting\">Window Glass Coating and Tinting</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Window Treatments - Draperies and Curtains\">Window Treatments - Draperies and Curtains</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Windows\">Windows</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wineries\">Wineries</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wines\">Wines</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Wireless Communications\">Wireless Communications</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Women's Clothing\">Women's Clothing</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Yoga\">Yoga</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Yogurt Shops\">Yogurt Shops</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Youth Organizations and Centers\">Youth Organizations and Centers</a><br>\n"; 
echo" <a href=\"cq.php?c=$c&q=Zoos\">Zoos</a><br>\n"; 
?>
</td></tr></table><br><br>


</body></html>